.github/workflows/gh.yml, .github/workflows/test.yml
https://github.com/rocky-linux/wiki.rockylinux.org/runs/4806328306?check_suite_focus=true
=> Check URLs - don't stop deployment on failure, though.

docs/contributing/index.md, docs/irc/.pages, docs/irc/index.md, docs/special_interest_groups/index.md
Attempt to fix TOC on some pages.
=> chore: dev -> main

docs/team/testing/index.md
This PR will add update Team page entry for Lukas Magauer and add Alan Marshal to the page.
=> Update Testing Team member info

docs/team/design/index.md, docs/team/web/index.md
- Added related info to design team page
- Added web team page
=> Update Team Pages

docs/team/testing/index.md
Add my own info to the team roster
=> Update team roster

Dockerfile, docs/team/testing/wiki_development_boxes.md
- Add Docker documentation to the wiki development boxes page
- Dockerfile will now install git at buildtime
=> Update dev box documentation

docs/team/testing/QA/Testcase_Debranding.md
This commit updates the debranding testcase with a more complete description of the workflow.
=> docs: update testcase_debranding

docs/special_interest_groups/sig_guide/release.md, docs/team/index.md, docs/team/testing/.pages, docs/team/testing/QA/Testcase_Basic_Graphics_Mode.md, docs/team/testing/QA/Testcase_Boot_Methods_Boot_Iso.md, docs/team/testing/QA/Testcase_Boot_Methods_Dvd.md, docs/team/testing/QA/Testcase_Debranding.md, docs/team/testing/QA/Testcase_Media_File_Conflicts.md, docs/team/testing/QA/Testcase_Media_Repoclosure.md, docs/team/testing/QA/Testcase_Media_USB_dd.md, docs/team/testing/QA/Testcase_Packages_No_Insights.md, docs/team/testing/QA/Testcase_Packages_No_RHSM.md, docs/team/testing/QA/Testcase_Repo_Compare.md, docs/team/testing/QA/Testcase_Template.md, docs/team/testing/index.md, docs/team/testing/qa_test_cases.md, docs/team/testing/release_criteria/.pages, docs/team/testing/release_criteria/.qa_testing_summary_template.md, docs/team/testing/release_criteria/.ver_qa_testing_go_no_go_template.md, docs/team/testing/release_criteria/r8/.pages, docs/team/testing/release_criteria/r8/8.6_qa_testing_go_no_go.md, docs/team/testing/release_criteria/r8/8.6_qa_testing_summary.md, docs/team/testing/release_criteria/r8/8_release_criteria.md, docs/team/testing/release_criteria/r9/.pages, docs/team/testing/release_criteria/r9/9.0_qa_testing_go_no_go.md, docs/team/testing/release_criteria/r9/9.0_qa_testing_summary.md, docs/team/testing/release_criteria/r9/9_release_criteria.md, docs/team/testing/release_criteria/release_criteria.md
This PR will bring the structure/reorg of Testing Team pages supporting different requirements and testcases for 8 and 9 into production wiki.
=> chore(merge) development → main

docs/team/testing/QA/Testcase_Basic_Graphics_Mode.md, docs/team/testing/QA/Testcase_Custom_Boot_Methods_Boot_Iso.md, docs/team/testing/QA/Testcase_VNC_Graphics_Mode.md, docs/team/testing/qa_test_cases.md, docs/team/testing/release_criteria/r9/9_release_criteria.md
This PR will add a testcase for r9 to document validation of VNC Graphics mode installations.
Resolves #36
=> Testing: Add Testcase_VNC_Graphics_Mode

docs/team/testing/release_criteria/r9/9.0_qa_testing_go_no_go.md, docs/team/testing/release_criteria/r9/9.0_qa_testing_summary.md
Merging and migrating from the QA testing done on Etherpad into the wiki.
=> Migration from Etherpad to wiki.

docs/team/testing/QA/Testcase_Post_Identity_Management.md, docs/team/testing/qa_test_cases.md, docs/team/testing/release_criteria/r8/8_release_criteria.md, docs/team/testing/release_criteria/r9/9_release_criteria.md
Created a first iteration of a IdM system install.
Comments about the setup are very welcome!
It was enough to get a quick setup for me in the past 👍🏻
=> Add Identity Management testcase

docs/team/testing/dev_guides/wiki_development_boxes.md
As I nearly completely moved to a Rocky Linux 9 machine, this is the way I'm working here now.
Maybe also interesting for others, so I added it to the docs.
=> Add toolbox dev box docs

docs/team/testing/dev_guides/commit_signing.md
Per Neil's request in #35 I have added a section on working with keyservers.
=> feat: Added section on publishing your key to a keyserver

docs/irc.md
Edits are bad.  Ask Mattermost users to limit them and give alternatives.
=> Etiquette for edits

docs/special_interest_groups/index.md
SIG AI was added to list of SIG's
=> SIG/AI Added to list

docs/team/testing/dev_guides/wiki_development_boxes.md
Small change to make sure the WSL docs are the correct once :)
=> Change Wiki dev box guide

docs/team/testing/QA/Testcase_Kickstart_Installation.md, docs/team/testing/QA/Testcase_Media_USB_dd.md, docs/team/testing/dev_guides/commit_signing.md, docs/team/testing/dev_guides/openqa_access.md, docs/team/testing/dev_guides/openqa_cli_post_examples.md, docs/team/testing/dev_guides/openqa_clone_custom_git_refspec_examples.md, docs/team/testing/dev_guides/openqa_clone_job_examples.md
Did some changes to the dev docs, to make the Linter happy, that doesn't understand where the links end.
Oh and formatting as well.
=> Fix some formatting and URIs to make the linter happy

docs/archive/legacy/mqtt_bus.md
feel free to comment/link to other outdated materials now...
=> add warning about git.c.o no longer being available

docs/events/FOSDEM_2024.md
if you don't fill in your information I get to make it up. that's the rules!
=> add schedule, times, add pablo to list

docs/team/community/index.md
This will update the community page with correct people and names
=> Update the community page with correct people and names

docs/team/community/.pages, docs/team/community/meeting-notes.md
add community meeting notes to wiki
=> Community meeting notes

docs/include/releng/version_table.md
=> fix 9.3 EOL date

docs/events/index.md
added upcoming events in September-November 2024
=> Update events for late 2024

docs/events/index.md
events updates for 2024 september-november
=> Update events for late 2024 (#88)

docs/team/community/event-reports/23SELF.md, docs/team/community/past-events.md
new document for event reports
=> add a report from fosdem 2024

docs/team/community/event-reports/24hacktoberfest.md
=> Social media post - LinkedIn

docs/team/community/event-reports/24hacktoberfest.md
24hacktoberfest social media post issue#97
=> 24hacktoberfest social media post issue#97

mkdocs.yml
Can you please review my PR and merge it?
Thanks.
Fixes #111
=> update copyright year

docs/contributing/index.md
- for some of the ways ...
- users to use our ...
=> fix: contributing: index.md remove unnecessary words

docs/contributing/git.md, docs/guidelines/git_guidelines.md, docs/special_interest_groups/current.md, docs/special_interest_groups/index.md, docs/special_interest_groups/sig_guide/index.md, docs/special_interest_groups/sig_guide/onboarding.md, docs/special_interest_groups/sig_guide/onboarding_leads.md
* update the sig guide to include onboarding guidelines
* add the git agreement text
* remove the line from git agreement regarding "no work on company devices" in line with [rocky-linux/board#8](https://git.resf.org/rocky-linux/board/issues/8#issuecomment-9505)
=> update sig guide, add git agreement. modify git agreement to not disallow company devices
